name: tickeaka-front

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5 # 가져다 쓸 auto tagging 프로그램
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # secrets.GITHUB_TOKEN 는 자동생성됨
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ticketaka-front
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "REACT_APP_KOPIS_SECRET=${{ secrets.KOPIS_SECRET }}"
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ticketaka-front:${{ steps.tag_version.outputs.new_tag }}
      - name: Checkout for Kustomize repository
        uses: actions/checkout@v2
        with:
          # kubernetes yaml 파일 저장
          repository: Project-Ticketaka/manifest # k8s yaml 파일이 있는 repo
          ref: main  # branch 이름
          # 내 repository에 push 하기 위한 Personal Access Token이 필요
          token: ${{ secrets.PAT }} # Github Action token을 발급받아서 repo secrect에 등록해줘야한다
          path: manifest # 최상위 경로로 repository와 동일하게 설정

          # 새 이미지 버전으로 파일의 태그값 수정
          # cd path 수정
          # kustomize로 image tag 값 변경
      - name: Update Kubernetes resources
        run: |
          pwd
          cd manifest/resources/front
          kustomize edit set image ${{ secrets.DOCKERHUB_USERNAME }}/ticketaka-front:${{ steps.tag_version.outputs.new_tag }}
          cat kustomization.yaml
      # 수정된 kustomization.yaml 파일 commit push
      - name: Commit manifest files
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          cd manifest
          git config --global user.email "rhj0830@gmail.com"
          git config --global user.name "HEEJAERO"
          git config --global github.token ${{ secrets.PAT }}
          git commit -am "Update image tag ${{ steps.tag_version.outputs.new_tag }}"
          git push -u origin main
